### ISSUE TITLE
PSL Criteria Checklist

### ISSUE THREAD

**Issue by MaxGhenis** [ganong-noel/ui_calculator#11]
The Policy Simulation Library appreciates the willingness of the `ui_calculator` maintainers to join the Library! The `ui_calculator` model is currently a PSL-incubating model. This issue highlights and provides a status update on progress towards the model obtaining PSL-cataloged status. The [criteria](https://pslmodels.org/Catalog/library_criteria.html) for inclusion in the [PSL catalog](https://pslmodels.org/Catalog/index.html) are outlined below, with notes on the status of this model's progress towards satisfying these criteria.

Once all "MUST" items are checked off, a PR will be opened to include a `PSL_catalog.json` configuration file in this repository.

**Acceptance Criteria for Transparency and Quality**

* [x]  Models MUST be released under an OSI-approved open source license or the Creative Commons Public Domain Dedication (CC0).
* [x]  Data MUST be publicly available, unless release is restricted by a third party.
* [x]  Projects MUST have unit tests
* [ ]   At least one test MUST generate key outputs from source materials, the test MUST be run with every new version, and the outputs of the test MUST be checked into the repository.
* [ ]  Projects MUST report names and contact information for at least one maintainer.
* [ ]  Projects MUST have a suggested citation.
* [x]  Projects MUST have a project overview.
* [x]  Projects MUST have installation directions.
* [x]  Project MUST be mirrored in the same GitHub organization as PSL, and therefore they MUST be under version control.
* [ ]  Projects MUST use a consistent versioning scheme, which SHOULD be semantic versioning.

**Community Criteria**
* [ ] Projects SHOULD report code coverage.
* [ ]  Projects SHOULD have a public roadmap.
* [ ]  Projects SHOULD have contributor documentation and guidelines.
* [ ]  Projects SHOULD have regular office hours, webinars, or standing meetings.
* [x]  Projects SHOULD list technical contributors.
* [ ]  Projects SHOULD list funders.
* [ ]  Projects SHOULD list user citations and case studies.
* [ ]  Projects SHOULD include subject matter tags
* [ ]  Projects SHOULD include a disclaimer.
* [x]  Projects SHOULD have a public issues tracker.
* [ ]  Projects SHOULD have a changelog.
* [ ]  Projects MAY have a Stack Overflow channel.
* [ ]  Projects MAY include a "News" translation of the changelog for users.
* [ ]  Projects MAY include criteria for participating in cross-model PSL initiatives.
* [ ]  Projects MAY include a link to a webapp version.
* [ ]  Projects MAY include a list of consultants.

**Interoperability Criteria**

* [x]   The source code SHOULD be written in an open source language.
* [ ]  A `PSL_catalog.json` configuration file to be used for cataloging these criteria MUST be included in the project's repository. Specific instructions for creating this file can be found in the [Catalog-Builder Documentation](https://github.com/PSLmodels/PSL-Infrastructure/tree/master/Tools/Catalog-Builder).

cc @peterobertson @ganong123 @jdebacker
